
export const metadata = {
    title: 'Cart - Be Vegan',
    description: 'Generated by create next app',
  }

export default function RootLayout({ children }) {
    return (
        <>
            {children}
        </>
    )
        
}