export const metadata = {
    title: 'Checkout - Be Vegan',
    description: 'Generated by create next app'
}
export default function RootLayout({ children }) {
    return (
        <>
            {children}
        </>
    )

}  